<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Surya Namaskar Article</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

</head>
<body>
  <?php include('header.php' ); ?>
<img src="images/surya-namaskaram-pose.webp" class="d-block w-100" width="1000" height="474" alt="...">
  <br>
 <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <h3>Benefits of Surya Namaskar
Surya Namaskar: Making the body a stepping-stone</h3>
            <p>Surya Namaskar means to bow down to the sun in the morning. The sun is the life source for this planet. In everything that you eat, drink and breathe, there is an element of the sun. Only if you learn how to better "digest" the sun, internalize it, and make it a part of your system, do you truly benefit from this process.</p>
            <p>The physical body is a fantastic stepping-stone for higher possibilities, but for most people it functions like a road block. The compulsions of the body do not allow them to go forward. Being in sync with the solar cycle is an important part of balance and receptivity, a means of taking the body to the point where it is no longer a hurdle.
            </p>
            <p>Surya Namaskar, which is known as "Sun Salutation" in English, is essentially about building a dimension within you where your physical cycles are in sync with the sun’s cycles, which run at about twelve-and-a-quarter years. It is not by accident but by intent that it has been structured with twelve postures or twelve asanas in it. If your system is in a certain level of vibrancy and readiness, and in a good state of receptivity, then naturally your cycle will be in sync with the solar cycle.</p>
            <p>Young women have an advantage in that they are also in sync with the lunar cycles. It is a fantastic possibility that your body is both connected to the solar cycle and to the lunar cycle. Nature has granted this advantage to a woman because she has been entrusted with the extra responsibility of propagating the human race. So she has been given some extra privileges. But many people don’t know how to handle the extra energy that is generated by that relationship and so they treat it as a curse and even a kind of madness, as evidenced by the word “lunar” turning into “loony.”</p>
            <h3>Importance of Surya Namaskar</h3>
            <p>Between the lunar cycle, which is the shortest cycle (a 28-day cycle) and the cycle of the sun, which is over twelve years, there are many other kinds of cycles. The word “cyclical” denotes repetition. Repetition means that in some way it is compulsive. Compulsiveness means it is not conducive for consciousness. If you are very compulsive, you will see that situations, experiences, thoughts and emotions will be cyclical. They keep coming back to you once in six months or eighteen months, three years or six years. If you just look back and see, you will notice this. If they come once in over twelve years, that means your system is in a good state of receptivity and balance. Surya Namaskar is an important process to enable that to happen. The sadhana is always to break the cycle so that there is no more compulsiveness, and you have the right kind of foundation for consciousness.</p>
            <p>The repetitive nature of cyclical movements or systems, which we traditionally refer to as samsara, is the necessary stability for the making of life. If it was all at random, it would not be possible to house a steady life-making machine. So, for the solar system and for the individual person, being rooted in cyclic nature is the firmness and steadiness of life. But once life has reached the level of evolution that human beings have reached, it is natural to aspire not just for stability, but for transcendence. Now, it is left to individual human beings either to remain trapped in the cyclical, which is the basis of stable physical existence, or to use these cycles for physical wellbeing and ride them and go beyond the cyclical.</p>
 </div>
    </div>
    </div>
 </article>
 <?php include('footer.php');?>
</body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</html>
